Feat:add contact page
zeshhaan/akbrothers pull request #8
Opened 2021-11-18 17:00 UTC by fathahul-mihad

2021-11-21 15:24 UTC, fathahul-mihad commented
any comments

2021-11-21 16:13 UTC, zeshhaan requested changes
- align the form heading to the form content
![image](https://user-images.githubusercontent.com/34814964/142769781-1a2dfb08-fde7-4f56-b995-498493880195.png)

- input text is very tiny, can you make it legible
![image](https://user-images.githubusercontent.com/34814964/142769831-0b1768ec-9e9a-4d80-b10e-fd19ea2b1d9f.png)

2021-11-21 16:17 UTC, zeshhaan reviewed
overall nice job, make the requested changes and send a PR. Thanks!

2021-11-21 16:17 UTC, zeshhaan commented on contact.html
> +         <input type="submit" value="Send" class="btn btn-dark">
- change it to button
- make the text similar to the one in the reference site. (capitalise it)
- add transition

2021-11-21 16:17 UTC, zeshhaan commented on contact.html
> +          Go for it.
add 'Go for it' on the next line. Check `<br>` tag

2021-11-21 16:22 UTC, zeshhaan requested changes
- give some space between the header image and main content
![image](https://user-images.githubusercontent.com/34814964/142770110-118d76cb-bdb7-4ceb-a44d-4328f57d2293.png)

- also give space between each form groups. Currently they seems all stacked and jammed together and creates confusion among users on what label for what input
![image](https://user-images.githubusercontent.com/34814964/142770189-2a948ff6-5993-4174-94bb-67f799496b59.png)


- align center
![image](https://user-images.githubusercontent.com/34814964/142770222-45ad00bf-461e-47d0-9c5c-825ce21d3adf.png)

2021-11-22 13:37 UTC, zeshhaan commented
@fathahul-mihad here is the embed code for map

> <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3895.3432945795043!2d74.98509531481706!3d12.49338999117091!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba4826bc4743a25%3A0x1741f97f8ee5ed4e!2sA+K+Brothers+Marketing!5e0!3m2!1sen!2sin!4v1563350691573!5m2!1sen!2sin" width="100%" height="460" frameborder="0" style="border:0" allowfullscreen></iframe>

2021-11-22 14:22 UTC, zeshhaan requested changes
#### Match it to the reference site adding padding to the x axes
![image](https://user-images.githubusercontent.com/34814964/142877322-9e95ef34-3e79-453f-a45a-43f82e2e0d70.png)


####  Add space between `form-group` divs
@fathahul-mihad the space between each form groups is so thin, so i think it would be better off if we give space between each of the form-groups.
![image](https://user-images.githubusercontent.com/34814964/142877133-ebdf351d-9353-4a9e-a603-42fd0529802b.png)

####  Also make the font label to `font-weight: 500;` instead of `font-weight: bold;`
![image](https://user-images.githubusercontent.com/34814964/142877584-87348141-07e4-44ef-9660-e68ad2974eda.png)

2021-11-22 14:22 UTC, zeshhaan commented on contact.html
> +         <input type="button" value="SUBMIT" class="btn-dark">
I know the referenced site is using an input field for form submit action. Can you instead make it a `button` element or `a` element?

2021-11-22 14:54 UTC, fathahul-mihad commented
done some changes 
any comments?

2021-11-22 15:20 UTC, fathahul-mihad commented
done

2021-11-22 15:27 UTC, zeshhaan commented
> #### Match it to the reference site adding padding to the x axes
> ![image](https://user-images.githubusercontent.com/34814964/142877322-9e95ef34-3e79-453f-a45a-43f82e2e0d70.png)
> 
> #### Add space between `form-group` divs
> @fathahul-mihad the space between each form groups is so thin, so i think it would be better off if we give space between each of the form-groups. ![image](https://user-images.githubusercontent.com/34814964/142877133-ebdf351d-9353-4a9e-a603-42fd0529802b.png)
> 
> #### Also make the font label to `font-weight: 500;` instead of `font-weight: bold;`
> ![image](https://user-images.githubusercontent.com/34814964/142877584-87348141-07e4-44ef-9660-e68ad2974eda.png)

@fathahul-mihad Don't forget to make the font-size changes too

2021-11-22 15:28 UTC, zeshhaan commented on styles.css
> +  font-weight: bold;
looks bit thicker, give it `500` instead of `bold`

2021-11-23 13:51 UTC, fathahul-mihad commented
make some changes

2021-11-24 14:10 UTC, merged